export const types = {
   'LOGIN_SUCCESS': 'LOGIN_SUCCESS',
   'LOGIN_FAILED' : 'LOGIN_FAILED',
   'FETCH_PROFILE_FAIL': 'FETCH_PROFILE_FAIL',
   'FETCH_PROFILE_SUCCESS' : 'FETCH_PROFILE_SUCCESS',
   'LOGOUT' : 'LOGOUT',
   'REGISTER_SUCCESS' : 'REGISTER_SUCCESS',
   'REGISTER_FAIL' : 'REGISTER_FAIL',
   

}

export const actionTypes = {
   LOAD_USER_TOKEN: "LOAD_USER_TOKEN",
   ERROR: "ERROR",
   EDIT_UPDATE: "EDIT_UPDATE"
};


 
